blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_listing, name='listing'),
    path('detail/<int:blog_id>/', views.blog_detail, name='blog_detail'),
    path('see_request/', views.see_request, name='see_request'),
    path('user_info/', views.user_info, name='user_info'),
    path('privet_place/', views.privet_place, name='privet_place'),
    path('staff_place/', views.staff_place, name='staff_place'),
    path('add_messages/', views.add_messages, name='add_messages'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls'), name='social'),
    path('projects/', include('projects.urls'), name='projects'),
    path('users/', include('users.urls'), name='users'),
    path('blog/', include('blog.urls'), name='blog'),

    path("__reload__/", include("django_browser_reload.urls")),
]

projects/urls.py
from django.urls import path

from projects import views

app_name = 'projects'

urlpatterns = [
    path('', views.all_projects, name='all_projects'),
    path('<int:pk>', views.project_detail, name='project_detail'),
]

users/urls.py
#!/usr/bin/env python3

"""
Users module routes.
"""

from django.urls import include, path

from users.views import dashboard, register

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', dashboard, name='dashboard'),
    path('register/', register, name='register'),
]

blog/models.py
#!/usr/bin/env python3

from django.db.models import (
    Model,
    CharField,
    TextField,
)


# Create your models here.
class Blog(Model):
    title = CharField(max_length=55)
    content = TextField()

projects/models.py
#!/usr/bin/env python3

"""
Django ORM models for projects app.
"""
from django.db.models import (CharField, DateTimeField, Model, TextField)


# Create your models here.
class Project(Model):
    title = CharField(max_length=100, blank=False, null=False, default='')
    description = TextField(blank=False, null=False, default='')
    short_description = CharField(max_length=255, blank=False, null=False, default='')
    technology = CharField(max_length=20, blank=True, null=False, default='Django')
    link = CharField(max_length=255, blank=True, null=False, default='')
    colaborators = CharField(max_length=255, blank=True, null=False, default='')
    image = CharField(max_length=255, blank=True, null=False)
    created_at = DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name_plural = 'Projects'
        ordering = ('id', 'title', 'technology')

users/models.py
from django.db import models

# Create your models here.

users/forms.py
#!/usr/bin/env python3

"""
Custom user registration form including email field.
"""

from django.contrib.auth.forms import UserCreationForm


class CustomUserRegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)

blog/views.py
#!/usr/bin/env python3

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages

from blog.models import Blog


# Create your views here.
def blog_listing(request):
    """
    It takes a request, and returns a response

    :param request: This is the request object that is sent to the view. It contains all the information about the request,
    including the HTTP method, the URL, the headers, the body, and so on
    :type request: HttpRequest

    :return: The data is being returned.
    :rtype: HttpResponse
    """
    data = {
        'blogs': Blog.objects.all()
    }

    return render(request, 'listing.html', data)


def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    data = {'blog': blog}

    return render(request, 'detail.html', data)


def see_request(request):
    text = f"""
    Some attributes of the request object:
    scheme: {request.scheme}
    path: {request.path}
    method: {request.method}
    GET: {request.GET}
    user: {request.user}
    """

    return HttpResponse(text, content_type='text/plain')


def user_info(request):
    text = f"""
    Some user attributes of the request object:
    username: {request.user.username}
    is_anonymous: {request.user.is_anonymous}
    is_authenticated: {request.user.is_authenticated}
    is_staff: {request.user.is_staff}
    is_superuser: {request.user.is_superuser}
    is_active: {request.user.is_active}
    """

    return HttpResponse(text, content_type='text/plain')


@login_required
def privet_place(request):
    return HttpResponse('This is a private place', content_type='text/plain')


@user_passes_test(lambda user: user.is_staff)
def staff_place(request):
    return HttpResponse('User is staff!', content_type='text/plain')


@login_required
def add_messages(request):
    username = request.user.username
    messages.add_message(request, messages.INFO, f'Hello {username}')
    messages.add_message(request, messages.WARNING, f'DANGER will get you {username}!')

    return HttpResponse('Messages Added', content_type='text/plain')

projects/views.py
#!/usr/bin/env python3

from django.shortcuts import render

from projects.models import Project


def all_projects(request):
    """
    It takes a request, gets all the projects, and renders a template with the projects

    :param request: This is the request object that is sent to the view
    :return: A list of all projects
    """
    projects = Project.objects.all()

    return render(
        request,
        'projects/all_projects.html',
        {
            'projects': projects
        }
    )


def project_detail(request, pk):
    """
    It takes a request and a primary key, gets the project with that primary key, and renders a template with the project

    :param request: The request object is the first parameter to every view. It contains information about the request that
    was made to the server
    :param pk: The primary key of the project we want to display
    :type pk: int
    :return: The project_detail view is returning a render of the project_detail.html template.
    """
    project = Project.objects.get(pk=pk)

    return render(
        request,
        'projects/detail.html',
        {
            'project': project
        }
    )

users/views.py
#!/usr/bin/env python3

"""
Routes for Users app.
"""

from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.urls import reverse

from users.forms import CustomUserRegisterForm


def dashboard(request):
    return render(request, 'users/dashboard.html')


def register(request):
    if request.method == 'GET':
        return render(
            request,
            'users/register.html',
            {'form': CustomUserRegisterForm}
        )
    elif request.method == 'POST':
        form = CustomUserRegisterForm(request.POST)

        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.backend = 'django.contrib.auth.backends.ModelBackend'
            new_user.save()
            login(request, new_user)

            return redirect(reverse('dashboard'))


def password_reset_complete(request):
    return render(request, 'users/registration/password_reset_complete.html')

blog/templates/detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="p-4">
    <h2>{{ blog.title }}</h2>
    <p>{{ blog.content }}</p>
</div>

<hr/>

<a href="{% url 'blog:listing' %}">All Blogs</a>

{% endblock %}

blog/templates/listing.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Blog Listing</h1>

{% if messages %}
<ul class="messages">

    {% for message in messages %}
    <li {% if message.tags %}
        class="{{ message.tags}}" {% endif %}>
        {{ message }}</li>
    {% endfor %}

</ul>
{% endif %}

<ul>
    {% for blog_post in blogs %}
        <li>
            <a href="{% url 'blog:blog_detail' blog_post.id %}">{{ blog_post.title }}</a>
        </li>
    {% endfor %}
</ul>

{% endblock %}

projects/templates/projects/all_projects.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container">
    <section class="md:h-full flex items-center text-gray-600">
        <div class="container px-5 py-24 mx-auto">
            <div class="text-center mb-12">
                <h1 class="text-4xl md:text-6xl text-gray-700 font-semibold">Projects</h1>
            </div>

            <div class="flex flex-wrap -m-4">

                {% for project in projects %}
                <div class="p-4 sm:w-1/2 lg:w-1/3">
                    <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden shadow-lg">
                        <img class="lg:h-72 md:h-48 w-full object-cover object-center"
                             src="{% static project.image %}"
                             alt="image">
                        <div class="p-6 hover:bg-indigo-700 hover:text-white transition duration-300 ease-in">
                            <h2 class="text-base font-medium text-indigo-300 mb-1">{{ project.title }}</h2>
                            <p class="leading-relaxed mb-3">{{ project.description }}</p>
                        </div>
                        <div class="p-6 flex items-center flex-wrap ">
                            <a href="{% url 'projects:project_detail' project.id %}"
                               class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Read
                                More
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</div>

{% endblock %}

projects/templates/projects/detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <div class="container">
        <div class="flex flex-wrap justify-center">
            <img src="{% static project.image %}" alt="" class="max-w-lg h-auto shadow-lg">
        </div>

        <div class="flex flex-col">
            <h1 class="text-center h1 display-2 mt-24">{{ project.title }}</h1>
            <p class="lead text-center">{{ project.description }}</p>
        </div>
    </div>

{% endblock %}

templates/base.html
{% load static %}
{% load tailwind_tags %}
{% load active_link_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="author" content="Daniel Andersson">
    <meta name="description" content="A simple portfolio app.">
    <meta name="robots" content="index, follow">
    <meta name="keywords"
          content="portfolio, web development portfolio, web developer portfolio, freelance">

    <title>Dannes Django App</title>

    <!-- TailwindCSS -->
    {% tailwind_preload_css %}
    {% tailwind_css %}

</head>

{% include 'header.html' %}

<body>
<div class="container">
    {% block content %}

    {% endblock %}
</div>
</body>

{% include 'footer.html' %}

</html>

templates/footer.html
{% load static %}

<footer class="fixed-bottom">
    <div class="container">
        <div class="row p-4">
            <p class="text-center">© 2021 Daniel Andersson</p>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}

{% load active_link_tags %}

<header>
    <nav class="relative w-full flex flex-wrap items-center justify-between py-3 bg-gray-900
                text-gray-200 shadow-lg navbar navbar-expand-lg navbar-light">
        <div class="container-fluid w-full flex flex-wrap items-center justify-between px-6">
            <div class="collapse navbar-collapse flex-grow items-center"
                 id="navbarSupportedContent1">
                <a class="text-xl text-white pr-2 font-semibold" href="#">Portfolio</a>

                <ul class="navbar-nav flex flex-row pl-0 list-style-none mr-auto">
                    <!--                    <li class="nav-item p-2">-->
                    <!--                        <a class="nav-link text-white opacity-60 {% active_link 'blog:listing' 'text-white opacity-100' %} hover:opacity-80-->
                    <!--                                  focus:opacity-80 p-0"-->
                    <!--                           href="{% url 'blog:listing' %}">Blog</a>-->
                    <!--                    </li>-->

                    <li class="nav-item p-2">
                        <a class="nav-link text-white opacity-60 {% active_link 'projects:all_projects' 'text-white opacity-100' %} hover:opacity-80
                                  focus:opacity-80 p-0"
                           href="{% url 'projects:all_projects' %}">Projects</a>
                    </li>

                    <li class="nav-item p-2">
                        <a class="nav-link text-white opacity-60  {% active_link 'dashboard' 'text-white opacity-100' %} hover:opacity-80
                                  focus:opacity-80 p-0"
                           href="{% url 'dashboard' %}">Users</a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
</header>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

users/templates/users/dashboard.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">

        <h1>User dashboard</h1>

        {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            <a class="nav-link" href="{% url 'password_change' %}">Change password</a>
        {% else %}
            <a class="nav-link" href="{% url 'login' %}">Login</a>
        {% endif %}

        <h3>Hello {{ user.username|default:'Guest' }}!</h3>

        {% if user.is_authenticated %}
            <p>Oh Summer, haha first race war, huh? </p>
            <p>Next saturday night we're sending you back to the future!</p>
            <p>Aww, gee, you got me there Rick... </p>
        {% endif %}

        <p>Hur står det till idag? </p>


    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}

    <h2>Register</h2>

    <form method="post" action="{% url 'register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>

    <a href="{% url 'login' %}">Back to Login</a>

{% endblock %}